### PR TITLE
Method to get the SID of the object

### PR DESCRIPTION
**Pull request by Mazwak**
Add dependency on bindata gem.
Cleaned up the gemspec.

What about switching to bundler btw ?

### CODE REVIEW

**Comment by ajrkerr** [comment]
Conflicts in this one.  I'd be happy to relinquish control of this gem to be honest. I haven't used or maintained it in years.

**Comment by Mazwak** [comment]
I would not be against maintaining it, but I never managed a gem before, do you know a good tutorial ?

I will check for the conflicts.

**Comment by Mazwak** [comment]
I have no conflicts on my side. What is yours ?

**Comment by ajrkerr** [comment]
Hmm... I merged in another pull request that wasn't one you submitted.  Try
rebasing ontop of my master branch and doing it again.

I don't have any resources for maintaining a gem. I forked this one in
glorious ignorance and maintained it while it was useful. Alas, I do not
spend as much time working on gems as I used to. I believe the toolset has
changed quite a bit. AD in particular was challenging because it was very
difficult to test. The original author included some code to build a small
LDAP server to approximate the environment.

Good luck!

Adam

**Comment by cthielen** [comment]
I've been keeping my branch up-to-date with this one. If somebody does take over this gem, could they announce it somewhere?

I'd be interested in filing issues in the very least. :-) Multi-server support is something my organization needs.

**Comment by ajrkerr** [comment]
I have added Mazwek as a branch maintainer.

**Comment by Mazwak** [comment]
Adam, do you want to leave the main repo under your account ?
I have already pointed to mine, but it is easily switchable.

**Comment by ajrkerr** [comment]
You can keep it pointed to yours.  I suspect it will be a nonissue.

**Comment by Mazwak** [comment]
@cthielen : 
Where do you think such an announcement should be made ?

**Comment by cthielen** [comment]
@Mazwak Sounds messy but if you want to be a strong maintainer I would recommend having ajrkerr, richardun and others update their READMEs to note your repo or ask them to make a proper fork of it. Any open issue threads on any of their repos would be a good place to advertise too.

Sounds like a bit of work but this gem could use some serious consolidation. It's a valuable piece of code.

**Comment by nextgenappsllc** [comment]
I made a pull request to Mazwak's fork which I just noticed has a bunch of pending requests. I see here that there is a few people maintaining this gem. Is there a consensus yet on the main repo? @cthielen I just checked yours out and you have the select attributes already in there which I just added myself so I might switch to yours.

**Comment by ajrkerr** [comment]
I'm not actively maintaining this project anymore. Closing.

**Pull request closed without merging**
